### ISSUE TITLE
[Exploration] Choice of JSON-API formatter

### ISSUE THREAD

**Issue by nono** [cozy/cozy-stack#10]
## [github.com/manyminds/api2go/jsonapi](https://github.com/manyminds/api2go)

The marshall/unmarshall uses an approach similar to JSON marshall/unmarshall in the standard lib, but it can be customized in many ways by implementing some interfaces. It looks like a low-level way to support JSON-API, with some code needed (not just a Struct description), but also the more extensible lib.

* Limitations: limited set of links (self, related and pagination), errors are in api2go package (not the jsonapi subset), not possible to customize self and related links in relationships
* 382 stars on github
* Last commit 27 days ago
* Extensions: building Rest API (with adapters for Gin and Gorilla)
* No active development, but seems well maintained

## https://github.com/google/jsonapi

The jsonapi StructTags tells this library how to marshal and unmarshal your structs into JSON API payloads.

* Limitations: no support for top-level errors, no links for relationships
* Extensions: none
* 224 stars
* Last commit 5 days ago
* No active development, but seems maintained (even if a PR is waiting for a maintainer)

## https://github.com/derekdowling/go-json-spec-handler

It works in two times: first, the document is unmarshalled to a generic struct (with Errors, Links, Data), and the attributes in data are just some Raw JSON, so they are unmarshalled later to a specific struct (User for example). This struct is just for the attributes, it doesn't have the ID. The attributes unmarshalling/marshalling is using the `json` tags, so it can be hard to reuse them for marshalling to JSON for CouchDB (no ID).

* Limitations: no one-to-one relationship, only self and related links
* Extensions: a JSONAPI client (jsc) and a web framework around goji2 (jsh-api)
* 26 stars on github
* Last commit 2 months ago
* The maintainer seems to merge pull requests in a timely manner, but didn't write code himself in the last 6 months

**Comment by tomsquest** [comment]
I think the link `api2go` should be: https://github.com/manyminds/api2go

**Comment by nono** [comment]
:disappointed: the 3 alternatives has big limitations that make [files](https://github.com/cozy/cozy-stack/blob/master/docs/files.md) impossible to implement without patching them (and not slightly)...

**Comment by nono** [comment]
Let's start with github.com/manyminds/api2go. We will have to modify it for our use cases, but it looks like the most solid base.
