### ISSUE TITLE
apt install cozy-stack => Impossible de trouver le paquet cozy-stack

### ISSUE THREAD

**Issue by jibe-b** [cozy/cozy-stack#1054]
En suivant la doc https://docs.cozy.io/fr/install/debian/ pour installer un cozy sur Ubuntu 16.04,

après avoir ajouté le repo de paquets debian pour Xenial, 

arrivé à l'installation de cozy-stack

https://hyp.is/GhqXOss2EeeP8le7G6iY-g/docs.cozy.io/install/debian/

pas de bol :

>E: Impossible de trouver le paquet cozy-stack

(il reste l'option de l'installation à partir de gitub)

**Comment by aeris** [comment]
Hello @jibe-b 

Pour les bugs de packaging, c’est plutôt [ici](https://github.com/cozy/debian-cozy) qu’il faudrait ouvrir des tickets, et pour des problèmes d’installation, ça serait plutôt [ici](https://forum.cozy.io/c/francais/hebergement).

Pour le moment, nous ne proposons pas de version stable, il faut donc utiliser uniquement `testing` ou `unstable`. Je suppose que c’est ce qui fait que tu n’as pas `cozy-stack` qui apparaît.

NB : On s’est rendu compte lors de notre meetup d’hier que `cozy-coclyco` rencontre des soucis avec Ubuntu Xenial qui est trop vieille pour pouvoir émettre des certificats Let's Encrypt correctement.
On va sûrement devoir passer sur Artful prochainement.
