### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-stack#1058]
# Needs for push notifications to be implemented

### Way for the application to define certificates and tokens.

Both GCM (Google Cloud Messaging) and APNS (Apple Push Notification Service)
necessitate some kind of credentials. The application need to be registered
to the stack if it needs to use the push notification service.

- Apple
  - Apple Push Certificate.
  - BundleId
  - Passphrase (optional)
  - Production Mode
- Android
  - GCM sender id
  - GMC apiKey

Here is the necessary data on the Parse platform to configure push notifications.

```
push: {
  android: {
    senderId: '', // The Sender ID of GCM
    apiKey: '' // The Server API Key of GCM
  },
  ios: {
    pfx: '', // The filename of private key and certificate in PFX or PKCS12 format from disk  
    passphrase: '', // optional password to your p12
    bundleId: '', // The bundle identifier associated with your app
    production: false // Specifies which APNS environment to connect to: Production (if true) or Sandbox
  }
}
```

Source: http://docs.parseplatform.org/parse-server/guide/#push-notifications

The stack should add configuration options in the `cozy.yml` for this. 

### Way for a device to register itself

Devices need to be registered so we can send them push notifications.
A `io.cozy.device` doctype could be created. It would store the necessary device information to be able
to push notifications. It needs to be cleaned up if the push notifications fails too much.

### Jobs to send notifications

A push attribute could be added to the notifications doctype that would send
the notification via mobile.

Way to bypass Google Services. microG is an open source implementation of the Google Services. It can be
used in place of Google Services but the phone needs to be rooted.

Source: https://github.com/microg/android_packages_apps_GmsCore

**Comment by nono** [comment]
Browsers also have an experimental push feature (with Service Workers): https://developer.mozilla.org/en-US/docs/Web/API/Push_API. We should probably think about it when we will create the API to register a client for notifications.

**Comment by nono** [comment]
It's available now, as described here: https://cozy.github.io/cozy-stack/notifications.html
