### ISSUE TITLE
'Regression' : 400 "Invalid JWT token" response on /remote/ image requests.

### ISSUE THREAD

**Issue by jacquarg** [cozy/cozy-stack#1106]
Hi,
Since a recent update of the stack in local, and since a few week in **.mycozy.cloud instances, I got request rejected by a 400 "Invalid JWT token" when I try to get images through `/remote/com.omdbapi.img`. Others call to the API and even other requests trough /remote still work. I can still make it work through an 2 month old cozy/cozy-app-dev docker image.

The request which fails dosen't use directly cozy-client-js, but directly an XmlHttpRequest, mimicking cozy-client-js source code, mainly : 
```
Promise.all([
         cozy.client.authorize(),
         cozy.client.fullpath(`/remote/${doctype}?${options.params}`),
       ]).then((res) => {
         const xhr = new XMLHttpRequest();
         xhr.open('GET', res[1]);
         xhr.setRequestHeader('Authorization', res[0].token.toAuthHeader());
```

You can check it here : https://gitlab.cozycloud.cc/gjacquart/lamusiquedemesfilms/blob/master/app/lib/img_fetcher.js#L5-30

**Comment by nono** [comment]
Hi,
can you try to add `xhr.withCredentials = true;` to your code? We have made a change that bind the authorization token of a web app to the session. It helps us to avoid rogue requests for a session revoked from the settings interface.

**Comment by jacquarg** [comment]
Thank you, it's working again !
