### ISSUE TITLE
concurrence entre les type de worker non fonctionnelle

### ISSUE THREAD

**Issue by sblaisot** [cozy/cozy-stack#1136]
Il semble que la stack priorise les type de worker (konnector, service, ...) et que par exemple konnecteur est traité avant service.

on sait par https://github.com/cozy/cozy-stack/blob/master/pkg/workers/exec/common.go#L20 que le nombre concurrent d'execution de konnecteur est limité à 2xCPU

Or, il semble que lorqu'on a une file de 50 konnecteurs en attente d'execution + 50 service en attente sur une machine configurée avec 20 worker, on se retrouve avec :
- 4 konnecteurs qui s'executent en parallèle
- aucun service ne s'execute tant que tous les konnecteurs n'ont pas été traités
- 4 services en parallèle sont lancés dès qu'il n'y a plus que 3 konnecteurs en execution. 

conclusion : d'après mes observations, on n'utilise jamais plus de 7 worker sur les 20 configurés.

Pouvez-vous faire en sorte que si les konnecteurs ne peuvent pas s'executer en raison d'une limite de concurrence configurée (actuellement hardcodée), cela n'empêche pas les autres types de jobs de s'exectuer ?

**Comment by jinroh** [comment]
Je ferme car #1140 doit résoudre ce problème. Merci de ré-ouvrir si nécessaire.
