### ISSUE TITLE
How to keep log level from a service to the stack

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-stack#1143]
When the stack retrieves the log of a service, it logs them by default as an error. It would be useful for the application if it could use `console.warn`, `console.error` and if the implied log levels were kept by the stack when logging.

Related code : 

https://github.com/cozy/cozy-stack/blob/15386c1a9d89416d944ea6f3f8da32bf9f699e54/pkg/workers/exec/common.go#L104

**Comment by ptbrowne** [comment]
One solution would be to require apps to log in JSON with the log level in the JSON object. The stack could then parse the JSON object and extract the log level from it. It has the disadvantage of having to parse each log.

**Comment by jinroh** [comment]
I think there already is a logger in [`cozy-konnectors-lib`](https://github.com/cozy/cozy-konnector-libs/blob/master/libs/logger.js). This logger outputs JSON strings containing the level of the log, allowing the stack be aware of this level.

For the [`console.*` methods](https://nodejs.org/api/console.html) from node, the output is either on stdout (for log, info, ...) or stderr (for warning and errors). Therefore, it is not possible directly for the stack to distinguish between a warn and an error.

A possibility would be to override the `console` object to output JSON objects, but I'm not sure it is a good option. It's more up to you at this point.

**Comment by ptbrowne** [comment]
Yes, the logger is there in cozy-konnector-libs, I agree that it makes sense for services to use the same method to log messages to stdout in JSON format.

By looking at the code of https://github.com/cozy/cozy-stack/blob/15386c1a9d89416d944ea6f3f8da32bf9f699e54/pkg/workers/exec/service.go, I see that `scanOuput` (should it be renamed scanOutput :) ?) does nothing for services so I guess we need to add JSON parsing to the scanOutput for services.

**Comment by jinroh** [comment]
Well, if you look at the [current service.go](https://github.com/cozy/cozy-stack/blob/master/pkg/workers/exec/service.go#L100-L119) on master (not an old commit), the JSON output is actually parsed by services.

**Comment by ptbrowne** [comment]
Wow weird, I don't know why I got on that commit :/
