### ISSUE TITLE
References are not deleted when a file is deleted

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-stack#1189]
I experienced a bug that should not happen too much in reality but that is a bit cumbersome
when dealing with demo instances.

Let's say I have a ACH file of albums referencing photos. The documents have `_id`s 

```
# Create some albums with ids demo1, demo2, demo3
# Those albums reference io.cozy.files
ACH import io.cozy.photos.albums.json

# Drop them
ACH drop  io.cozy.photos.albums.json

# Recreate some albums demo1, demo2, demo3 but from a different file
ACH import io.cozy.photos.albums2.json 
```

The problem here is that the references created in step 1 are still there after step 2 (and 3), meaning that I see photos that should not be there in my albums.

**Comment by nono** [comment]
> References are not deleted when a file is deleted

@ptbrowne I do not understand your issue. The references are persisted in the `io.cozy.files` documents. So, when a file is deleted, references are also deleted.

**Comment by ptbrowne** [comment]
The files are not deleted in this case. OK I understand why the files are still in the new albums. My ACH files had the same ids for the albums. Why are the references in the files and not in the albums ?

**Comment by nono** [comment]
The `referenced_by` mechanism on files is generic and one of the goal is that the drive application (web, mobile, and desktop) to alert the user when he try do trash/delete a file that is used by an album, a connector, a playlist, a bill, etc. The drive application doesn't have permissions on all the doctypes, and we don't have cross-databases indexes, so it was decided to put the reference on the `io.cozy.files` doctype.

**Comment by ptbrowne** [comment]
OK I understand better.

> to alert the user when he try do trash/delete a file that is used by an album, a connector, a playlist, a bill, etc.

Interesting. For now the connectors do not put a reference in `reference_by` when they link a bill to a file. The bill has an invoice field that contains the id of the file. [io.cozy.bills docs](https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.bills.md#iocozybills).

It has been made this way since this field should be used in Banks (to display a link to the file next to the transaction line) and Banks has no permissions on the files. Do you think we should also a reference to the bill in the file ?

**Comment by nono** [comment]
> Do you think we should also a reference to the bill in the file?

Yes, it would be a good idea to do so.
