### ISSUE TITLE
SVG served as text/xml

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-stack#1217]
I added some SVG icons for permissions in https://github.com/cozy/cozy-stack/pull/1213. They were not showing on the auth page because they were served as text/xml : 

![image](https://user-images.githubusercontent.com/1606068/35633245-085158f0-06a9-11e8-84b8-96db71e3ef85.png)

I checked what was different with others SVG shown on this page, and the only difference was the presence of the following line on the newly added files : 

```xml
<?xml version="1.0" encoding="UTF-8"?>
```

It seems the stack is wrongly serving SVG files that begin with this line as text/xml files.

**Comment by jinroh** [comment]
Fixed by https://github.com/cozy/cozy-stack/pull/1216 and https://github.com/cozy/statik/commit/089a2f6969450d5e768ebe26ec26cf4f9cf80628. Thanks !
