### ISSUE TITLE
[VFS swift][layout V2] version container not marked To-Be-Deleted when detroying instance

### ISSUE THREAD

**Issue by sblaisot** [cozy/cozy-stack#1239]
When destroying an instance, 2 of the 3 swift containers of this instance are marked "To-Be-Deleted" (`cozy-instance` and `data-instance`).
Unfortunately, the third container `cozy-instance-version` is not marked To-Be-Deleted.

See https://github.com/cozy/cozy-stack/blob/master/pkg/vfs/vfsswift/impl_v2.go#L117,L118 for container deletion and https://github.com/cozy/cozy-stack/blob/master/pkg/vfs/vfsswift/impl_v2.go#L59,L61 for container creation.

**Comment by nono** [comment]
Fixed by 9022b82c734bf85d1e752c52c0263c89e37aaf3d
