### ISSUE TITLE
Tarball pour la compilation, versionning des dépendances Go

### ISSUE THREAD

**Issue by ArchangeGabriel** [cozy/cozy-stack#1301]
Deux choses :
1. On peut avoir les tarballs pour compiler cozy-stack qui correspondent à ce qui est utilisé pour Debian ? Idéalement les attacher aux releases tagguées sur ce dépôt. @aeris m’a montré le script pas très sorcier mais qui requiert un compte Transifex, ce qui n’est pas idéal.
2. Ce script fait un `go get` qui récupère la moitié de GitHub (bon j’exagère, juste 75 dépôts en tout), pour lesquels il ne me semble pas évident quelle version du code est récupérée. La branche `master` de chaque dépôt je suppose ?

Merci !

**Comment by nono** [comment]
Salut,

1. Normalement, il y a déjà les binaires attachés aux releases ici : https://github.com/cozy/cozy-stack/releases

2. Oui, on utilise toujours la branche `master` pour les dépendances. C'est sur notre todo-list de versionner ça. On avait commencé à regarder `dep`, mais ça ne marchait pas du premier coup et le lendemain, `vgo` était annoncé. `vgo` ne marchait pas non plus du premier coup, c'est encore un prototype, donc on attend un petit peu qu'il se stabilise pour s'y remettre.

**Comment by ArchangeGabriel** [comment]
1. Je veux pas les binaires (qui sont effectivement bien attachés), je veux les sources (celles utilisées pour construire le paquet debian). ;) Le but étant de construire le paquet pour ArchLinux.
2. OK, je vois, merci ! C’est vrai que c’est un peu compliqué l’éco-système go et la gestion des dépendances, c’est un sujet qui revient souvent parmi les devs Arch…

**Comment by aeris** [comment]
Il faut que je trouve comment faire manger le .tar.gz à aptly. Je ne vois pas d’option pour lui dire d’intégrer les sources aussi, alors qu’elles sont bien présentes dans le dépôt de publication et qu’il semble faire des choses avec…

```
[+] cozy-stack_2018M1S6-1_source added
[+] cozy-stack_2018M1S6-1_amd64 added
```

Mais je ne trouve rien dans le dépôt de sortie :cry:

**Comment by ArchangeGabriel** [comment]
J’ai cherché très vite fait sur le net, rien trouvé de spécial à part qu’il semble attendre des fichiers .dsc pour décrire les sources.

Mais à défaut si tu peux attacher le tarball aux côtés des binaires sur la (dernière) release GitHub ici, ça m’ira pour l’instant. ;)

**Comment by aeris** [comment]
C’est fait :)

**Comment by ArchangeGabriel** [comment]
Merci !

**Comment by ArchangeGabriel** [comment]
On peut avoir ça pour la nouvelle release aussi ? Et avec le SHA signé comme la dernière fois, c’était super. ;)

**Comment by aeris** [comment]
Ça va arriver, la release côté debian est en cours :)
Et il faut vraiment que j’arrive à comprendre pourquoi aptly ne publie jamais les sources…

**Comment by aeris** [comment]
J’ai normalement pérenniser la publication.
Les sources devraient normalement être dans le dépôt Debian de manière classique.
Voir https://apt.cozy.io/debian/pool/testing/c/cozy-stack/ pour la version actuelle :smiley:

**Comment by daftaupe** [comment]
Excellent @aeris ! Merci beaucoup :)

**Comment by ArchangeGabriel** [comment]
@aeris Nickel ! C’était quoi le bug aptly du coup ?

**Comment by aeris** [comment]
En fait il faut détruire et recréer les publications en ajoutant l’architecture « source »… :woman_facepalming:

**Comment by ArchangeGabriel** [comment]
Soit. Content que ça fonctionne en tout cas.
