### ISSUE TITLE
[Exploration] Choice of storage provider interface

### ISSUE THREAD

**Issue by nono** [cozy/cozy-stack#14]
## What we want?

The Cozy stack will be able to store the binaries on several providers: local filesystem, Swift from Open Stack, in memory (for tests), etc. The metadata are kept in CouchDB and the Rest API will be the same, no matter what the storage provider is. So, we need to define a Go interface for our storage providers.

## github.com/blang/vfs

* Available storages: local FS, memory
* Available wrappers: readonly, mount, prefix
* 119 stars on github
* Last commit 1 month ago
* No open issues/PR
* No active development

## github.com/spf13/afero

* Available storages: local FS, memory, SFTP
* Available wrappers: basepath, readonly, regexp, http, copy on write, cache on read
* 702 stars on github
* Last commit 9 days ago
* Some PRs are waiting that a maintainer looks at them, but globally it has regular work
* 2 other projects that rely on afero:
  - https://github.com/fcavani/aferoboltdb
  - https://github.com/ryansb/af3ro

## github.com/thoas/gostorages

* Available storages: local FS and S3
* 20 stars on github
* Last commit 2 months ago
* No active development

**Comment by nono** [comment]
Afero has the best documentation, is the more complete and solid package. We will use it.

**Comment by VojtechVitek** [comment]
Very helpful. Thank you for documenting this. 👍
