### ISSUE TITLE
support federated share api

### ISSUE THREAD

**Issue by violoncelloch** [cozy/cozy-stack#1422]
support for the federated share api to share to other cozy instances and to other servers like Nextcloud or Owncloud would be nice.
see:
https://lukasreschke.github.io/OpenCloudMeshSpecification/#federated-sharing

**Comment by nono** [comment]
Hello,

thanks for the suggestion. We are currently working on a way to share files, photos and other documents between cozy instances. You can see what we want to do here: https://docs.cozy.io/en/cozy-stack/sharing-design/.

It won't be compatible with the federated share API. It's too limited and doesn't fit very well the cozy model.
