### ISSUE TITLE
Upload button missing if window width is between 770 and 1024 px

### ISSUE THREAD

**Issue by yurkobb** [cozy/cozy-stack#1427]
There's a media query bug at the list of files view in Cozy Drive: the Upload button is missing in the "middle-size" layout - it's neither in the menu nor in the toolbar.

**Comment by blaubachn** [comment]
I think this has been fixed.

![large](https://user-images.githubusercontent.com/5402635/41611270-f88086e8-73b4-11e8-820b-c2b4253a0d1e.PNG)

![medium](https://user-images.githubusercontent.com/5402635/41611271-f89a2ada-73b4-11e8-85d3-b35654625307.PNG)

![small](https://user-images.githubusercontent.com/5402635/41611272-f8b2fda8-73b4-11e8-867d-01df96358d06.PNG)

**Comment by yurkobb** [comment]
I confirm it is fixed for me. Thank you!
