### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by peperunas** [cozy/cozy-stack#1432]
Hello!

I think it would be great to have an official Docker image.
It makes easier to test Cozy.

**Comment by vsellier** [comment]
Hi @peperunas 
I started something few days ago to easily bootstrap a cozy cloud install using docker : https://github.com/vsellier/easy-cozy/ . It's at the early stage so any feedbacks are welcome ;)

I hope this can help you

**Comment by aeris** [comment]
There is another attempt here : https://github.com/rgarrigue/docker-gozy
And also mine here : https://github.com/aeris/cozy-docker

**Comment by peperunas** [comment]
Hello @vsellier, @aeris,
thanks for your heads-up!

I do really appreciate them but I would still like an official container in order to minimize the fragmentation of these unofficial containers.

I prefer the official container since, hopefully, it will be supported throughout Cozy's development and won't shutdown suddenly. This may happen when a private maintainer doesn't need the app anymore.

**Comment by peperunas** [comment]
Any progress on the issue yet?

**Comment by aeris** [comment]
Hello @peperunas 
There is a new unofficial docker version here : https://github.com/aeris/cozy-docker
Currently it doesn't support konnectors, there is a little bit of work to have them working on docker.

**Comment by chmac** [comment]
Any plans from the @cozy team to support docker?

For me personally, it would signal that Cozy is dedicated to making it easy to self host. Without that, I think it's unlikely I'll switch.

**Comment by nono** [comment]
@chmac no, we don't any plan to support docker on the short term. We have seen that it is a bit tricky to support it (for example, CouchDB has some issues when running in docker). And the debian/ubuntu packages already take us time to support, so we prefer to invest this time to develop more features.

**Comment by chmac** [comment]
@nono Awesome, thanks for the clarity. I can understand that adding more distribution styles makes more work, and if CouchDB already has docker issues, that doesn't sound like fun at all! Thanks for the quick response, I appreciate it.

**Comment by nono** [comment]
https://docs.cozy.io/en/tutorials/selfhosting/docker/
