### ISSUE TITLE
OAuth2 & URL redirect. Should the parameter be code instead of access_code?

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-stack#1488]
From @prebours on https://github.com/cozy/cozy-client/issues/91

Hello:

As per the OAuth2 [documentation](https://aaronparecki.com/oauth-2-simplified/), it seems that the redirect url should contain `code` as a parameter. But cozy-stack returns `access_code`. The problem is that the OAuth implementation of cozy does not work well with external libraries. FYI, I am using `httr` that is a *R* package specialized in REST queries.

This is the code found in *cozy-stack-client*:

```
getAccessCodeFromURL(pageURL, stateCode) {
    if (!stateCode) throw new Error('Missing state code')

    const params = new URL(pageURL).searchParams
    const urlStateCode = params.get('state')
    const urlAccessCode = params.get('access_code')

    if (stateCode !== urlStateCode)
      throw new Error('Given state does not match url query state')

    return urlAccessCode
  }
```

**Comment by nono** [comment]
Yup, my mistake. We should move from `access_code` to just `code` to be compliant with OAuth 2.0, and to make the migration smoother, I think we should send the string 2 times, one for `access_code` and one for `code` for some time before deprecating `access_code`.
