### ISSUE TITLE
/data/<doctype>/_all_docs returns a design doc amonst the results

### ISSUE THREAD

**Issue by goldoraf** [cozy/cozy-stack#1514]
[The "list all docs" route](https://github.com/cozy/cozy-stack/blob/master/docs/data-system.md#list-all-the-documents) returns a design document amongst the results. It's a bit annoying because paginating the results using `offset` and `limit` becomes a lot more complicated if we have to filter that document clientside.

**Comment by nono** [comment]
Yes, but the `_all_docs` route is really just a proxy to CouchDB (it just checks the permissions) and I don't think we want to diverge from the CouchDB response here.

**Comment by nono** [comment]
A `/data/:doctype/_normal_docs` route has been added for this use case: https://docs.cozy.io/en/cozy-stack/data-system/#list-all-the-documents-alternative
