### ISSUE TITLE
Permission on stack admin passphrase are too open

### ISSUE THREAD

**Issue by bobsaintcool** [cozy/cozy-stack#1662]
Hey, 

I think cozy-stack set too open permission on the admin-passphrase file from *0444* it will be good to switch to *0440*.

See [config.go:113](https://github.com/cozy/cozy-stack/blob/master/cmd/config.go#L113) or [config.go:119](https://github.com/cozy/cozy-stack/blob/master/cmd/config.go#L119).

**Comment by nono** [comment]
Hello,

thanks for the bug report. You are right, we should use _0440_ for this file. It will be fixed by #1664

**Comment by nono** [comment]
The pull request has been merged. Thanks!

**Comment by bobsaintcool** [comment]
Great, thanks!
