### ISSUE TITLE
External permissions

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-stack#1680]
Right now, for external permissions, the store will rely on a new property `partenership.name` of the manifest to show to the user the external permissions that are necessary for the konnector. There will still be hardcoded custom logic in the store to support the external permissions.

How is it going to evolve in the future ? Apparently there have been some discussions on how to handle this in the Mattermost channels, but I would prefer if there was a written document expliciting the design decisions behind this.

PR on the store implementing hard coded logic: https://github.com/cozy/cozy-store/pull/505/files
PR on the registry describing the new attributes: https://github.com/cozy/cozy-apps-registry/pull/25/files

**Comment by nono** [comment]
Sorry, I don't have information about what is planned for external permissions.

**Comment by nono** [comment]
@gregorylegarec do you have some hints for us?

**Comment by ptbrowne** [comment]
This is not critical for me or for Banks, I have created this issue merely to evacuate this from my head, so we do not forget, feel free to close if you put this somewhere else like Trello.
