### ISSUE TITLE
Link binary releases statically instead of dynamically

### ISSUE THREAD

**Issue by moritzheiber** [cozy/cozy-stack#1787]
Due to the fact that all (newer) releases appear to be linked dynamically you're unable to run them with distributions that aren't linking against Glibc, Alpine Linux in particular (which is a popular distribution for containers). I would love to have them linked statically instead to be able to build (very) small containers.

The releases I tried it with was 1.2.1.

Thanks!

**Comment by nono** [comment]
Sorry, it's not something we want to support. You can compile yourself the stack from the source.

To give more context: golang binaries are statically linked for all the go modules, but the go runtime is still dynamically linked to the libc. It's possible to do statically compile go programs, but it's less straight-forward, and from what I head, it can introduce some subtle changes (like `/etc/hosts` being ignored). If you want to do in this direction, https://dominik.honnef.co/posts/2015/06/statically_compiled_go_programs__always__even_with_cgo__using_musl/ is a good start.
