### ISSUE TITLE
Malformed permissions verbset make installation fails

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-stack#1831]
If an app serve a manifest containing malformed permissions verbset (for example `["ALL", "GET"]`, it does not throw any error from front tests to registry, until app installation.

Imho this should not be a reason for making an app installation fail.

**Comment by nono** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Permettre d'installer une app dont le manifeste a une permission pour ALL et GET](https://trello.com/c/KSHlYppw/1358-permettre-dinstaller-une-app-dont-le-manifeste-a-une-permission-pour-all-et-get)
