### ISSUE TITLE
Permission page has no margins

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-stack#1884]
Device iPhone S simulator

<img width="430" alt="image" src="https://user-images.githubusercontent.com/465582/57082713-98ee8080-6cf7-11e9-978a-228ffca9464b.png">

**Comment by ptbrowne** [comment]
Seems to happen when the name of the cozy is fairly long. The "chip" containing the name cannot be broken and streches the page.

**Comment by GoOz** [comment]
New design provided by @joel-costa 
https://app.zeplin.io/project/584a6f4e838090371f59518f/screen/5ccff338936b89681a93a69e
https://app.zeplin.io/project/584a6f4e838090371f59518f/screen/5ccff338f7cf61683e1f9203

The goal being to break the instance at the domain first and break the slug in last resort.

**Comment by ptbrowne** [comment]
Ca m'a l'air donc d'etre plus en problème de Chip que de la page d'onboarding ? Il faut pas que la Chip puisse dépasser de son conteneur en somme.

**Comment by GoOz** [comment]
Oui et non. 
Ce n'est définitivement pas un problème de l'onboarding.
Ce n'est pas vraiment la faute du Chip non plus.
C'est un problème de contenu. Étant donné que l'url est une string sans espace et qu'il n'y a aucune instruction concernant le word breaking, le navigateur ne coupe pas. S'il y avait ne serait qu'un espace alors pas de problème.
<img width="1078" alt="Screenshot 2019-05-06 11 01 41" src="https://user-images.githubusercontent.com/1280069/57215833-5d510080-6fee-11e9-9145-01e53b0ddd69.png">

Je suis pas certain que ce soit le job du Chip de donner ces instructions. J'imagine qu'il faudrait en fait un composant juste pour faire ce job afin de pouvoir récupérer ce comportement dans n'importe quel autre contexte que le Chip. Au mettre titre que les composants `Ellipsis ` et `MidEllipsis` finalement.

**Comment by ptbrowne** [comment]
> Je suis pas certain que ce soit le job du Chip de donner ces instructions. J'imagine qu'il faudrait en fait un composant juste pour faire ce job afin de pouvoir récupérer ce comportement dans n'importe quel autre contexte que le Chip. 

Les 2 ne me paraissent pas antinomiques.

Je serais pour faire le composant qui a le bon comportement et l'utiliser dans Chip. Personnellement, en tant que dev, je n'ai pas envie qu'une Chip puisse peter mon design si j'oublie de la wrapper dans le Composant (ou classe) qui fixe le word-breaking.

**Comment by GoOz** [comment]
Yep yep on peu faire ça aussi, je voulais surtout pouvoir l'utiliser ailleurs que dans le Chip mais je peux le mettre par défaut dans le Chip aussi :)

**Comment by GoOz** [comment]
Ok, so I've been looking for solutions. And I think there's no need for another UI Component.

We can add by default (or with an option) the already existing utility class `u-breakword`on the Chip component in order to get the string to break.

As for the chosen point of break like the mockup suggested, I think it would be best if the app/stack is the one in charge of that by adding a `<wbr />`  HTML element wherever it fits best.

@ptbrowne I'm wondering, do you think the Chip component should always have the class ? Or should I make it a prop, even if it is `true` by default, so you can disable it if needed?

**Comment by ptbrowne** [comment]
> @ptbrowne I'm wondering, do you think the Chip component should always have the class ?

Yes. I do not see a case where a Chip should override its container. If we stumble upon a case where it should, it will be very easy to add the property.
