### ISSUE TITLE
insert-asset uses cache version if an asset with given shasum exists

### ISSUE THREAD

**Issue by cedricmessiant** [cozy/cozy-stack#1900]
#### What did you do?

If we give a shasum to `cozy-stack config insert-asset`, it uses the version of the package that matches this shasum if it has it in cache even if we want to insert a newer version.

#### What did you expect to see?

I expect the stack to display an error telling me that the given shasum is not good for this version/package.

#### What did you see instead?

For example:
`# cozy-stack config insert-asset --context default --name /js/myapp.min.js --url https://unpkg.com/myapp@1.0.1/dist/cozy-bar.min.js --shasum shasum-for-1.0.0`

inserts myapp v1.0.0 whereas the user asks for V1.0.1

**Comment by nono** [comment]
It has been fixed by https://github.com/cozy/cozy-stack/pull/1936
