### ISSUE TITLE
Slow updates for references

### ISSUE THREAD

**Issue by Gara64** [cozy/cozy-stack#1903]
This is related to #1902 

I measured the execution time taken to add new files references. It turns out the time is mainly consumed on the CouchDB update queries, here: https://github.com/cozy/cozy-stack/blob/master/web/files/references.go#L165-L180

It takes 20-25ms per document update, so adding 1000 references in a single query takes +20 000ms to complete.

**Comment by Gara64** [comment]
Note the problem is the same for references deletes

**Comment by nono** [comment]
@Gara64 we can close this issue with your work on #1904, right?

**Comment by Gara64** [comment]
Right!
