### ISSUE TITLE
Not possible to specify a double event trigger

### ISSUE THREAD

**Issue by doubleface** [cozy/cozy-stack#1948]
The "@event io.cozy.identities:CREATED io.cozy.identities:UPDATED" to specify a trigger in apps manifest is accepted by the resulting trigger only handles the first event.

I get around this by specifying two services in the manifest which lead to the same service code : 

```js
  "services": {
    "myselfFromIdentities": {
      "type": "node",
      "file": "services/myselfFromIdenties/home.js",
      "trigger": "@event io.cozy.identities:CREATED"
    },
    "myselfFromIdentitiesUpdated": {
      "type": "node",
      "file": "services/myselfFromIdenties/home.js",
      "trigger": "@event io.cozy.identities:UPDATED"
    }
  }
```

https://docs.cozy.io/en/cozy-stack/jobs/#event-syntax states that : 

```js
  "services": {
    "myselfFromIdentities": {
      "type": "node",
      "file": "services/myselfFromIdenties/home.js",
      "trigger": "@event io.cozy.identities:CREATED io.cozy.identities:UPDATED"
    }
  }
```

should be possible.

**Comment by nono** [comment]
@doubleface did you try `@event io.cozy.identities:CREATED,UPDATED`?

**Comment by nono** [comment]
It works, and the doc has been updated with https://github.com/cozy/cozy-stack/pull/1951
