### ISSUE TITLE
cannot find package "github.com/robfig/cron/v3"

### ISSUE THREAD

**Issue by LM1LC3N7** [cozy/cozy-stack#2037]
Hello,

I am trying to create a docker image. I am using golang:1.12-stretch in order to get sources and compile the binary.
But it seems there is an error in a dependency:

```bash
Step 2/10 : RUN go get github.com/cozy/cozy-stack
 ---> Running in 920cdf368ebc
package github.com/robfig/cron/v3: cannot find package "github.com/robfig/cron/v3" in any of:
        /usr/local/go/src/github.com/robfig/cron/v3 (from $GOROOT)
        /go/src/github.com/robfig/cron/v3 (from $GOPATH)
The command '/bin/sh -c go get github.com/cozy/cozy-stack' returned a non-zero code: 1
```

`github.com/robfig/cron/v3` doesn't exist on github, but `github.com/robfig/cron` does.

**Comment by nono** [comment]
Hello,

this error comes when the stack is built without using go modules. Can you try again with the `GO111MODULE=on` env variable set? It should force the use of go modules.

**Comment by LM1LC3N7** [comment]
Thank you very much 🙂
