### ISSUE TITLE
Konnectors: Exit status 55

### ISSUE THREAD

**Issue by fbetil** [cozy/cozy-stack#2093]
Bonjour,

Après installation sur mon Raspberry (Raspbian GNU/Linux 9 (stretch)), tout semble fonctionner correctement sauf les konnecteurs (Free, Paje, Bouygues, ...). J'obtiens systématiquement l'erreur "exit status 55" dans le fichier debug (ici pour Bouygues):

`Sep 29 15:29:05 cozy cozy[339]: time="2019-09-29T15:29:05+02:00" level=debug msg="response: {\"docs\":[\r\n{\"_id\":\"216aa1ba3a6838d07e7ace5ac805e227\",\"_rev\":\"3-70c13fbfe87ffe50b7c010e39f97b612\",\"domain\":\"mondomain.org\",\"prefix\":\"cozy5d8dd69ba6fe415c9e318d11bad90701\",\"worker\":\"konnector\",\"trigger_id\":\"216aa1ba3a6838d07e7ace5ac805dccb\",\"message\":{\"account\":\"216aa1ba3a6838d07e7ace5ac805bd5e\",\"konnector\":\"bouyguestelecom\",\"folder_to_save\":\"216aa1ba3a6838d07e7ace5ac805cd4a\"},\"event\":null,\"manual_execution\":true,\"state\":\"errored\",\"queued_at\":\"2019-09-29T15:11:23.171264148+02:00\",\"started_at\":\"2019-09-29T15:11:23.552268108+02:00\",\"finished_at\":\"2019-09-29T15:11:28.102410379+02:00\",\"error\":\"exit status 55\"}\r\n]}" domain=mondomain.org nspace=couchdb`

Par avance merci de votre aide.
Cordialement,

**Comment by nono** [comment]
Bonjour,

c'est difficile de répondre avec si peu d'informations. J'ai trouvé deux fils de discussions sur le forum qui peuvent être en rapport : 

- https://forum.cozy.io/t/collect-sur-raspbian-9/5599
- https://forum.cozy.io/t/les-connecteurs-nimportent-rien/5437

**Comment by doubleface** [comment]
Je viens de voir ça : https://github.com/google/nsjail/issues/80

**Comment by nono** [comment]
Je ferme l'issue ici, au profit des échanges sur le forum.
