### ISSUE TITLE
Config enhancement

### ISSUE THREAD

**Issue by tomsquest** [cozy/cozy-stack#21]
## To be done

_Work started in:_ https://github.com/tomsquest/cozy-stack

* [x] Look in current directory for a config file
* [x] Handle error when reading config file
* [x] Create a `Config` struct containing the app configuration (see below)
* [x] Add a `config` command to display the parsed configuration (eg. `./cozy-stack config`)
* [x] Inject `Config` where needed, eg. `cmd/status.go` needs the database url

## Already done in `master`

* [x] Parse command line argument with Cobra
* [x] Read config file with Viper
* [x] Integrate Cobra with Viper

## The `Config` struct

This structure contains the final configured key-value pairs.

Goals:
* Be injected into code which depends on configuration
* Not having reference/depends the global `spf13/viper` in application code
* Level of indirection between the config flag and the real values (eg. renaming `prod` to `production` internally)

Pseudo-code for Config:

```go
type Config struct {
	Mode mode 
	Database struct {
	        Url string
        }
}

config := Config{
	Mode: Production(),
	Database: {
		Url: "http://db:5984",
	},
}
```

@nono @aeris preliminarily feedback appreciated

**Comment by nono** [comment]
ping @aenario

**Comment by nono** [comment]
@tomsquest looks good to me. I'd also be interested by having the possibility to override the config file with env variables (e.g. `COZY_MODE` for the mode).

**Comment by tomsquest** [comment]
@nono Yes, this would be the defaults, and they are enforced by Viper.
AFAIK flag > env > config

From `viper.go`:
```go
// overrides
// flag
// env
// config
// key/value store
// default
```

**Comment by nono** [comment]
Nice!

**Comment by tomsquest** [comment]
PR in #24

# Info

* Configured params:

```
$ go run main.go --help
Cozy is a platform that brings all your web services in the same private space.
With it, your web apps and your devices can share data easily, providing you
with a new experience. You can install Cozy on your own hardware where no one
profiles you.

Usage:
  cozy [flags]
  cozy [command]

Available Commands:
  config      Display the configuration
  serve       Start the stack and listens for HTTP calls
  status      Check if the HTTP server is running

Flags:
  -a, --address string   Address on which the server will listen (default "localhost")
  -c, --config string    config file (default is $HOME/.cozy.yaml)
  -m, --mode string      server mode: development or production (default "development")
  -p, --port int         Port on which the server will listen (default 8080)

Use "cozy [command] --help" for more information about a command.
```

* `config/Config.go` is a struct containing the binded variables
  * It contains a reference to itself and is accessed by `config.GetConfig()`. This is how Viper works (`viper.GetViper()`)

* Viper and Cobra works together to read, in order of importance:
  * params: `./cozy-stack --port 1234`
  * environment vars: `COZY_PORT=1234 ./cozy-stack`
  * an **optional** config file, in the current folder, in $HOME, in `/etc/cozy`: `echo "port: 1234" > .cozy.yaml`
  * the optional config file can be provided in the command line: `./cozy-stack --config /tmp/cozy.yaml` and an error is risen it the specified file does not exist

* Added a `config` command

It describes the **runtime** configuration:

```shell
$ go run main.go --mode production --port 1234 config
{
  "Mode": "production",
  "Address": "",
  "Port": 1234,
  "Database": {
    "URL": ""
  }
}
```

# More details

* Each Cobra's command needs to call `Configure` to be bound to Viper, this was the trick to glue all the things together
* This is Cobra which gives the *default* param values, not Viper
* Viper can be the last resort, if a config value must exist and it is not a Cobra flag (then we need `viper.SetDefault("hiddenParam", "42")`

# Improvements

* Use Dependency Injection of `Config` instead of the singleton access, ie. `config.GetConfig()`

# WIP

* [ ] Bind `database.url`
* [ ] Display usage when no command given (this was the behavior of master and I don't know why this isn't the case now)

**Comment by tomsquest** [comment]
Closing as #24 was merged.
