### ISSUE TITLE
Wrong job message

### ISSUE THREAD

**Issue by doubleface** [cozy/cozy-stack#2159]
When a job is started with api

ex: 
```javascript
    await this.stackClient.fetchJSON('POST', `/jobs/queue/${workerType}`, {
      data: {
        type: JOBS_DOCTYPE,
        attributes: {
          arguments: {
    		message: {
      		  "name": "test",
      		  slug: 'banks'
            }
    	  },
          options: options || {}
        }
      }
    })
```

The job is run but the resulting io.cozy.jobs get the following structure :

```js
      ...
      "worker": "service",
      "message": {
        "message": {
          "name": "test",
          "slug": "banks"
        }
      }
      ...
```

Note the "message" inside "message"

This causes some problems to display the job in bender.

**Comment by nono** [comment]
`arguments` is a synonym for `message`. Both terms are used for historical reasons, and to preserve the compatibility (but it should be something to improve). Can you try to create the job with this?

```js
    await this.stackClient.fetchJSON('POST', `/jobs/queue/${workerType}`, {
      data: {
        type: JOBS_DOCTYPE,
        attributes: {
          arguments: {
      		name: 'test',
 		slug: 'banks'
    	  },
          options: options || {}
        }
      }
    })
```

**Comment by doubleface** [comment]
The problem was in the way the service was triggered. If we remove the "message" level in arguments, the service will be triggered the same way and bender will display the service correctly.
