### ISSUE TITLE
cozy instance creation issue

### ISSUE THREAD

**Issue by renjith-jr** [cozy/cozy-stack#2161]
I started the cozy server using cozy-stack serve command and i could successfully start the server. It shows the below response
`INFO[0000] Started in-memory broker for 16 workers type  nspace=jobs
Ready and waiting for connections:
  http server major started on "localhost:8080"
  http server admin started on "localhost:6060"
`

Then i tried creating cozy instance using below command. 

`cozy-stack instances add --passphrase cozy --apps drive,photos,settings "cozy.tools:8080"`
But it throws the below error 

`Failed to create instance for domain cozy.tools:8080
Error: Forbidden: bad passphrase`

Please help me to resolve this issue.

**Comment by nono** [comment]
Hello, have you defined a passphrase for the administration API (like explained on https://docs.cozy.io/en/cozy-stack/config/#administration-secret)?
