### ISSUE TITLE
Add completion for fish shell

### ISSUE THREAD

**Issue by mamyn0va** [cozy/cozy-stack#2337]
Currently, only bash and zsh completions are supported by cozy-stack CLI. As fish shell is getting more and more popular among user-friendly shells, I think it deserves its own completion.

**Comment by nono** [comment]
We are using a library called cobra for managing the CLI options parsing. There is a PR opened for adding fish completion, but it has not been merged yet: https://github.com/spf13/cobra/pull/754

**Comment by mamyn0va** [comment]
Is this independent from cozy-stack ? I mean, as soon as cobra will merge this PR, will the fish completion be working in cozy-stack, or will you have to create a completion file, as for bash and zsh ?

**Comment by nono** [comment]
When the PR will be merged, we will update https://github.com/cozy/cozy-stack/blob/master/cmd/completion.go, and use it to generate the completion file for fish.

**Comment by mamyn0va** [comment]
Ok, great, I close the issue.
