### ISSUE TITLE
settings/context returns 404 if there is no context

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-stack#2410]
The `/settings/context` endpoint returns a 404 error if there is no context defined for the instance. 

This is not documented here https://docs.cozy.io/en/cozy-stack/settings/#get-settingscontext. 

From a front end point of view, it doesn't make sense to get a 404 if there is no context and force us to add a special case for this route to handle the 404 detail: "no config defined...". Is there a particular reason to do that? Can't we just return a 200 with an empty object?

**Comment by nono** [comment]
> Is there a particular reason to do that?

Well, I can see how responding a 404 to inform the web app that the context has not been configured can make sense. But it is not used by the web apps, and I can see how it can make things more complicated that it should.

> Can't we just return a 200 with an empty object?

Yes, we can.
