### ISSUE TITLE
swift and keystone v3

### ISSUE THREAD

**Issue by flo-dhalluin** [cozy/cozy-stack#2416]
Hi, 

I am self-hosting on ovh, using swift as as storage. ovh is removing keystone v2 in a few weeks, and I can't find info on how to configure swift ( I don't even remember how did I managed to configure keystone v2 in the first place).

I'll have a look at the code to check this.

**Comment by nono** [comment]
It can be configured in config file: https://github.com/cozy/cozy-stack/blob/master/cozy.example.yaml#L55-L71

**Comment by nono** [comment]
As I don't see what more we can do on this issue, I close it. But feel free to reopen it if you have a more precise question to ask.

**Comment by flo-dhalluin** [comment]
The example config file lacks a bit of details, for example, how do I pass the keystone url ? 
My config ( working with keystone v2 ) is : 
`` url: swift:///openstack/?AuthURL=https://auth.cloud.ovh.net/v2.0&ProjectName=xxx&ProjectID=xxx&UserName=xxx&Password=xxx&Region=GRA&UserDomainName=None

just switching AuthUrl to v3 leads me to 404 errors when I restart cozy-stack.

**Comment by sblaisot** [comment]
We use keystone v3 in our production platform so this should definitely work.

Here is a sample keystone v3 configuration:

```
swift+https://auth.cloud.ovh.net/v3?ProjectName=xxx&ProjectID=xxx&UserName=xxx&Password=xxx&Region=GRA&UserDomainName=None
```
