### ISSUE TITLE
Doc OpenIdConnect

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-stack#2455]
https://github.com/cozy/cozy-stack/blob/master/docs/delegated-auth.md#open-id-connect

"OpenID Connect can also be used, and is more adapted when the" 

I think it miss the end of the sentence here.

**Comment by nono** [comment]
Yes, the end of the sentence is missing. But I don't remember what I wanted to say...

**Comment by nono** [comment]
Fixed by https://github.com/cozy/cozy-stack/commit/7850f83b0b8fe6f39e5b28131e5532c8ce3567a0
