### ISSUE TITLE
DOC : broken link in jobs documentation

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/cozy-stack#2591]
There is a broken link https://docs.cozy.io/en/cozy-stack/jobs/#permissions_9 on "permission document"
File here : https://github.com/cozy/cozy-stack/blob/master/docs/jobs.md
I don't know where the link is supposed to point to.

PR : https://github.com/cozy/cozy-stack/pull/2592

**Comment by Crash--** [comment]
I think it should point to : https://docs.cozy.io/en/cozy-stack/permissions/

**Comment by JF-Cozy** [comment]
Oui je viens tout juste de voir ça ! Je corrige 👍

**Comment by JF-Cozy** [comment]
Fixed

**Comment by Crash--** [comment]
tips: Si dans ton commit message sur ta correction tu mets : fix #2591 quelque part, quand la PR est mergée, ça fermera automatiquement l'issue ;)
