### ISSUE TITLE
Installation via Docker

### ISSUE THREAD

**Issue by JulesMichael** [cozy/cozy-stack#276]
Bonjour,

Après plusieurs tentatives d’installation de Gozy sur ma machine, je me demandais si vous aviez prévue la mise en place d'un Dockerfile (ou d'un sript bash) pour simplifier le déploiement de Gozy.

**Comment by nono** [comment]
Bonjour,

oui, c'est prévu et même déjà en parti en place. On fournit une image docker adaptée pour les développeurs d'applications: https://cozy.github.io/cozy-stack/client-app-dev.html#with-docker.

Cozy-stack n'est pas encore prêt pour être utilisé en production, mais quand il le sera, nous travaillerons également pour simplifier son déploiement pour des contextes autres que juste développer des applications.

**Comment by JulesMichael** [comment]
C'est exactement ça que je cherchais !
Merci pour la rapidité et la qualité de la réponse.
