### ISSUE TITLE
Configure TravisCI to run go test

### ISSUE THREAD

**Issue by tomsquest** [cozy/cozy-stack#31]
Currently, Travis does not run `go test` and it would be nice.

_I did not manage to find how to tell Travis to use my fork instead of original/upstream one_

**Comment by nono** [comment]
Well, travis does run `go test -v ./...` for each build currently (see https://travis-ci.org/cozy/cozy-stack/builds/165511983#L345 for example). It's [the default test script](https://docs.travis-ci.com/user/languages/go/#Default-Test-Script). Or, maybe I didn't understand your issue.

> I did not manage to find how to tell Travis to use my fork instead of original/upstream one

Good question, I don't see an easy way to do that. Did you try adding [`go_import_path: github.com/cozy/cozy-stack`](https://docs.travis-ci.com/user/languages/go/#Go-Import-Path) to travis.yml?

**Comment by tomsquest** [comment]
Sorry, jumped too quickly to this conclusion (local build failing, did a quick check on the .travis.yml...).

For the Travis error, I will give it a try. From the default test script, all should work by default, which was not the case (I think some package were pulled from the original repo and mixed with the fork's packages).

Closing this issue in between.
