### ISSUE TITLE
CouchDB Doc interface

### ISSUE THREAD

**Issue by jinroh** [cozy/cozy-stack#36]
Working on the interaction between the VFS and Couch, I have some suggestions to change the current API of our data layer, mainly on the `couch.Db` type. I'll try to list the different options that I've seen and the and the one I think is best.

I hope this is not something part of a previous discussion. I have not seen it.

## `Doc` as a `map[string]interface{}`

The current one. While it's maybe the most direct and basic solution, and perfect for the lose `/data` api, it does not give us many possibilities for inner usages.

Working with map is not very idiomatic when we would like to enforce more type safety on the documents we store in database. And converting maps to structs is neither efficient nor desirable all over our code base.

Finally, map being implemented as a hashmap, it is less efficient than a packed `struct`.

## `Doc` as a `interface{}`

By using the empty iface type, we have one level more of indirection. It allows us to use type structs or maps, which one is better to represent our data.

Although we have to rely on reflection and convention (an `_id` field on the struct for instance) to solve the "id problem". We do not gain much in type safety... while Go can provide us better possibilities by representing this behaviour through methods.

## `Doc` as a `interface { SetID, GetID }`

Finally, we can enforce the existence of setter/getter on the type's methods to solve this issue. We of course still have one level on indirection more, but I think it is a useful abstraction in this case with better type safety and more idiomatic.

Regarding the `rev`, we can either enforce `SetRev/GetRev` methods on the doc types through the interface, or returning the `rev` at the return site of the `CreateDoc` func:

```go
type Doc interface {
  GetID() string
  SetID(string id)
}

func CreateDoc(..., doc Doc) (rev string, error)
```

I think this last solution is better. See an implementation [here](https://github.com/jinroh/cozy-stack/commit/c3bb5673afa9d12fefd1f277f036db5bb2b03d14).

What do you think ?

**Comment by nono** [comment]
:+1: for GetRev/SetRev

@aenario you have also asked to add `Doctype` to the interface. Am I right?

For a map, it can return one the field. For a struct, it can be hardcorded:

```go
type File struct {
  // ...
}

func (f *File) Doctype() string {
  return "io.cozy.files"
}
```

**Comment by jinroh** [comment]
Ok so we all agree an the third solution. Let's agree on the interface per se.

Can we agree on this ? :

```go
type Doc interface {
  ID() string
  Rev() string
  DocType() string // <- or a DocType type string maybe... we'll see later

  SetID(id string)
  SetRev(rev string)
}
```

I've removed the `Get`s, because I think they're ugly 😄

**Comment by nono** [comment]
It's good for me!

**Comment by jinroh** [comment]
I'll make a PR with these changes.
