### ISSUE TITLE
A lot of bodies not closed

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-stack#3611]
It seems that almost no http body are closed after they are used and from my experience this can be a big issue at scale.

## Context

This is a copy of the `Response.Body` documentation:
 
```	// The http Client and Transport guarantee that Body is always
	// non-nil, even on responses without a body or responses with
	// a zero-length body. It is the caller's responsibility to
	// close Body. The default HTTP client's Transport may not
	// reuse HTTP/1.x "keep-alive" TCP connections if the Body is
	// not read to completion and closed.
	Body io.ReadCloser
```

This means that without the call to `Close` you are forcing all your clients to recreate a TCP connext and SSL handshake optionnaly for all your requests. For what I know you also keep the response in memory until your connection timeout

## Impacts

The fact that you connection hang until its timeout with the response buffer in memory can cost a lot of RAM.

I know for sure that recreating a TCP connection + SSL can cost a lot of CPU. In one of my professional project I have saved ~30% of CPU on a proxy juste by improving the connexion reuse.

EDIT: After some thoughts this 30% number doesn't really concern you because the performance issue is bounded to the service throughput and the ~30% CPU improvement was done on a service with ~10 000/qps. I guess you don't have this kind of scale yet.

## Proposed Solution 1

I have tried to write a commit for fixing the issue but it's way to big to be merged (https://github.com/Peltoche/cozy-stack/commit/637d3637d03b3e8f906cf83a21a0abfd56428737) and it add a lot of boilerplate inside the tests.

## Proposed Solution 2

I also give a try refactor somes test with the lib https://github.com/gavv/httpexpect which I know is really great (https://github.com/Peltoche/cozy-stack/commit/9f43720345e43ea67ca87b7756d228609e6e8fcc). As explained inside the topic one of the advantage of this lib is to handle the Body.Close for use.

So if you like my work on https://github.com/Peltoche/cozy-stack/commit/9f43720345e43ea67ca87b7756d228609e6e8fcc I would like to propose you to continue my refactoring and fixing the Body.Close in the same time, package by package.

## Proposed Solution 3

I can make you a commit fixing all the calls except the tests. This would be big but not enormous but it would be impossible to enable the linter in order to avoid this kind of issue in the futur.

**Comment by nono** [comment]
Hi, sorry for the delay.

I agree that we should close our `Response.Body` in production code. I have done it on the critical parts, like the connections to CouchDB, for the reasons you explain. But I have been more sloppy on other places.

I think one way we can advance on the subject could be:

1. fix the production code
2. enable the linter via another configuration file to disable running it on test files (temporary)
3. work on the tests to use httpexpect (I agree it improves tests)
4. when/if we can migrate all the tests, we can fusion the two configuration file for linters in one.

Are you OK with that?

**Comment by Peltoche** [comment]
Hi :wave: 

My first message make the issue as terrible because the linter return a lot of errors but after a deeper look it seems that the linter have a lot of limitations. Id doesn't handle the body closed inside an another function.

So I totally agree with you plan, I had the same in mind but if we want to enable the linter in prod it would require to move the body closing next to the requests. This will make a lot of duplicate juste for making the linter happy. 

Personnaly I think it's not terrible but it's still a good idea because this linter have a lot of value but this is your choice to make :smile: 

I will start to migrate the tests to httpexpect ASAP but it will take some time.

**Comment by Peltoche** [comment]
It's done! 

After a loooooong and tedious refactoring all the tests have moved on `gavv/httpexpect` and we can better see the actual `bodyclose` errors and hope to be able to activated soon.

Have a propose a bunch of PR which, once merged, should allow to enable the `bodyclose` linter and ensure that no body have been leaved unclosed.

**Comment by Peltoche** [comment]
Final note: It seems that there is far fewer body not close than what I have expected. 95% of them was inside the tests.
