### ISSUE TITLE
Moving back from https://github.com/cozy/afero to https://github.com/spf13/afero?

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-stack#3781]
Hi @nono  :wave: 

From what I have understood the repo `spf12/afero` have been forked in order to fix a `Readdir` function: https://github.com/spf13/afero/commit/991b95a9f96f97636555cf27b346ff453f580003. This change have been proposed and merged into the main line: https://github.com/spf13/afero/pull/170.

Since then it seems that the main line have received a lot of updated and we didn't maintain the fork. At the moment the fork is 142 commits behind. 

Maybe we should considere to move back the the main line and delete this fork?

**Comment by nono** [comment]
We should look for doing that. I think there were other commits in our fork, but I don't remember what.

**Comment by Peltoche** [comment]
https://github.com/spf13/afero/compare/master...cozy:afero:master to be precise.

Seems to have two main commits:

[Return error in Readdir on regular mem file](https://github.com/spf13/afero/commit/991b95a9f96f97636555cf27b346ff453f580003) fixing https://github.com/spf13/afero/issues/169 -> This is the one merged (https://github.com/spf13/afero/pull/170)

and


[Fix renaming a dir with sub-directories](https://github.com/spf13/afero/commit/12b7d27decdd033919e7e01195e97dd3d9403ce8) -> There is no linked issues or corresponding pulls requests but the code seems to be present in master too: https://github.com/spf13/afero/blob/12b7d27decdd033919e7e01195e97dd3d9403ce8/memmap.go#L309, the test created in the commit is present in master -> https://github.com/spf13/afero/blob/12b7d27decdd033919e7e01195e97dd3d9403ce8/memmap_test.go#L453

After this check it looks safe to me to move to the main branch. I will create a PR for it and we will see what the CI says

**Comment by nono** [comment]
> [Fix renaming a dir with sub-directories](https://github.com/spf13/afero/commit/12b7d27decdd033919e7e01195e97dd3d9403ce8) -> There is no linked issues or corresponding pulls requests but the code seems to be present in master too: https://github.com/spf13/afero/blob/12b7d27decdd033919e7e01195e97dd3d9403ce8/memmap.go#L309

No, this page says:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

And I don't see my code on spf13's master. There is no `TestMemFsRenameDir` on https://github.com/spf13/afero/blob/master/memmap_test.go, and https://github.com/spf13/afero/blob/master/memmap.go#L298-L323 doesn't look like my patched version.

**Comment by nono** [comment]
Oh, and I found the PR I have made: https://github.com/spf13/afero/pull/239. And there was also an update here: https://github.com/spf13/afero/pull/320. Let's try again.

**Comment by Peltoche** [comment]
Do you take care of creating the new pull request or should I do it?

**Comment by nono** [comment]
I have rebased https://github.com/spf13/afero/pull/239 and pinged the maintainer

**Comment by nono** [comment]
But you can make a PR to spf13/afero to fix their issues with statikcheck. I think that the version of statikcheck they use is no longer compatible with go 1.17 and go1.18.

**Comment by nono** [comment]
My PR has been merged. Let's hope that the maintainer also make a new release :crossed_fingers:

**Comment by Peltoche** [comment]
Damn that's quick!

> But you can make a PR to spf13/afero to fix their issues with statikcheck. I think that the version of statikcheck they use is no longer compatible with go 1.17 and go1.18.

I don't understand what issue are you talking about?

**Comment by Peltoche** [comment]
The release is already done -> https://github.com/spf13/afero/releases/tag/v1.9.4

**Comment by nono** [comment]
> I don't understand what issue are you talking about?

It was https://github.com/spf13/afero/actions/runs/4250910073/jobs/7392677488, but the maintainer has fixed it with https://github.com/spf13/afero/commit/a6023d20a1baa574245078a87c5258c7d66d4358#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R19

**Comment by Peltoche** [comment]
I update #3783 to the version v.1.9.4 and we should be ok.
