### ISSUE TITLE
Discussion: Code coverage integration?

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-stack#3798]
Hi @nono 

It would be great to have some coverage information. This could help us to know if a part of the codebase need more tests. 

What do you think of adding a coverage integration like https://about.codecov.io/?

**Comment by nono** [comment]
Hi, we had code coverage a long time ago. It was codecov (cf https://github.com/cozy/cozy-stack/pull/113). But, we weren't using it, having no time to improve our code coverage, and we finished by removing it. We may try again.

**Comment by Peltoche** [comment]
Yeah!  :confetti_ball: 

I will propose a PR
