### ISSUE TITLE
can't make cozy working behind cloudflared

### ISSUE THREAD

**Issue by answer35** [cozy/cozy-stack#3834]
Hi,
I recently heard of your solution and I have to admit that I am quite interested to use it self-hosted.
I followed the tutorial available and was able to go all the way to cozy install. I haven't made cozy-coclyco yet since few earlier test were unsuccessful.
I decided to stopped at cozy install and create my cozy-stack instance. it created successfully. But now I am having issue to connect on it.
I am using cloudflared to connect through all my different services so I made a new hostname on cloudflared dashboard connecting to ipaddress:8080, then I made another CNAME to subdomain but no matter what I am not able to make it works.
What am I missing ?

**Comment by nono** [comment]
Hi,

by default `cozy-stack` binds on localhost, which is not accessible from Internet. You can try with the `--host=0.0.0.0` option.
