### ISSUE TITLE
[Exploration] ID vs QID vs Type

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-stack#40]
## State of the union

The current state of the codebase and documentation is as follow
```http
GET http://example.cozycloud.cc/data/io.cozy.events/111aaa111
{
"_id":"io.cozy.events/111aaa111"
}
```
which translates in couchdb
```
"_id":"io.cozy.events/111aaa111"
```

This solution has some advantages 

1. No special field in couchdb and no need to change of the document on every `/data` request
2. Open to changes in how we store data : all ids are uniques, so if we finally want to put all documents in a single couchdb base (in data-proxies or in main stack), it wont change the external API.
3. The doctype is visible in both the URL, which allow some optimisation (discard body if doctype doesnt match permissions), and the document itself which simplify interfacing with JS frameworks (no need to manipulate a `[type, map[string]string]` tupple)

However, it cause a few issues : 

1. ID means either `111aaa111` or `io.cozy.event/111aaa111` depending on where you are in codebase, these could be alleviated by a convention. Either, 
a. ID and QID (qualified ID)  or 
b. UUID and ID.
2. IDs have to be generated on go side following the convention doctype+UUID, this means it is impossible to simply replicate from another couchdb database, unless it respect the same convention.
3. Extracting the doctype from the QID requires [string manipulation](https://github.com/aenario/cozy-stack/blob/707b3f3096619ca8d5fe55a3b6549d2cc631c636/couchdb/couchdb.go#L56-L63). This is inefficient.

## Plan B - `_type` field

An alternative could be 
```http
GET http://example.cozycloud.cc/data/io.cozy.event/111aaa111
{
"_id":"111aaa111",
"_type":"io.cozy.events"
}
```
which would translate in couchdb
```json
{
"_id":"111aaa111", 
"$x-cozy-type":"io.cozy.events"
}
```
Advantages
1. It is clear what ID is.
2. It is straightforward to extract the Type from a JSON doc.

Inconvenients
1. Need to parse and change the json on every `/data` request, we cant store the `_type` field in couchdb (couchdb doesnt accept fields which name starts with _)
2. IDs are not unique, there could be conflict among fixed id ( like `io.cozy.folders/pictures` vs `io.example.irc_chans/pictures`) if we attempt to merge our bases. This could be aleviated by forcing fixed id to include the doctype, but then we get weird URL `/data/io.cozy.folders/io.cozy.folders.root`)

**Comment by nono** [comment]
Fixed by #42
