### ISSUE TITLE
Can't install cozy stack

### ISSUE THREAD

**Issue by Djoow** [cozy/cozy-stack#4103]
Hello,

I am following the self hosting documentation : https://docs.cozy.io/en/tutorials/selfhosting/selfhost-debian-pkg/

While running the command `sudo apt install cozy`, I am getting this : 
```sh
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cozy : PreDepends: cozy-couchdb (>= 2.0) but it is not going to be installed or
                    couchdb (>= 2.0)
        Depends: cozy-stack but it is not going to be installed
```

Then, if I try running `sudo apt install cozy-couchdb` to see what's wrong, it is getting me : 
```sh
The following packages have unmet dependencies:
 cozy-couchdb : Depends: couch-libmozjs185-1.0 but it is not going to be installed
```

And finally, if I run `sudo apt install couch-libmozjs185-1.0`, here is what I get : 
```sh
The following additional packages will be installed:
  libnspr4
The following packages will be REMOVED:
  linux-image-4.19.0-25-arm64 linux-image-arm64
The following NEW packages will be installed:
  couch-libmozjs185-1.0 libnspr4
0 upgraded, 2 newly installed, 2 to remove and 5 not upgraded.
Need to get 1001 kB of archives.
After this operation, 225 MB disk space will be freed.
Do you want to continue? [Y/n]
```

Surprisingly, it tries to remove my linux kernel package, which is what I suppose to be the problem.

Do you have any idea about how to resolve that dependecy resolution problem ?

Additional information about my setup : 
- device: arm64 (a freebox delta if you want to know)
- distribution: debian 10

Thank you very much for your help

Djow

**Comment by sblaisot** [comment]
Hi,

You can try installing couchdb from upstream package: https://docs.couchdb.org/en/stable/install/unix.html

This should do the trick

Please note that precompiled debian packages are quite old (we need to refresh all that self-hosting packages later this year) and you should get better result with compiling from souce as documented in https://docs.cozy.io/en/tutorials/selfhosting/selfhost-ubuntu-sources-en/ (this doc is primarily targetting ubuntu but should work on debian too)

**Comment by Djoow** [comment]
Hi @sblaisot,

Thank you for your answer, I managed to correctly install cozy cloud from sources as you mentionned !
