### ISSUE TITLE
Cannot login to cozy instance

### ISSUE THREAD

**Issue by ibaraki-douji** [cozy/cozy-stack#4484]
I setup a new Cozy stack using docker compose (from "cozy-stack-compose" repo), and after creating an instance, i cannot login to the instance.

I know the password is right because the API request works and i'm redirected to the home application, tho i'm directly back to the login page just after ...
![image](https://github.com/user-attachments/assets/1af4f259-c7d0-47eb-a4e8-8ee9537f29af)
(screenshot filtred for "Documents" only and keep history to keep even when i change pages)

Looking at the console i can see an error :
`time="2024-10-30T13:03:05.305Z" level=error msg="cannot open the geodb: no such device" nspace=sessions`

And i have no idea of what it could be ...

**Comment by ibaraki-douji** [comment]
After more search i found out that :
1 - The error is because i didn't have the `geodb: ""` saved into the yml (as it's not in the example from the repo)
2 - Because i was using "cozy.localhost"  as my test domain, when setting the cookie the domain fallback to "localhost" and the browser did not liked that (so changed to "cozy.local.host")

**Comment by EricGuic** [comment]
Hi @ibaraki-douji, did you figure out how to correct this "geodb" error, I facing the same here.
My cozy is set behind Swag reverse proxy and a proper domain name. I can reach the login page behind cozy.mydomain.fr, but after I enter my password and click Login, web browser try to load home.cozy.mydomain.fr and gets stuck on a white blank page.

Logs are : 
`
==========================================================================
Starting /usr/local/bin/docker-entrypoint.sh, Tue Nov 19 20:54:49 CET 2024
==========================================================================
useradd: warning: the home directory /var/lib/cozy already exists.
useradd: Not copying any file from skel directory into it.
Waiting for CouchDB to be available...
wait-for-it.sh: waiting 60 seconds for couchdb:5984
wait-for-it.sh: couchdb:5984 is available after 1 seconds
Init CouchDB databases, nothing will happen if they already exists...
error=file_exists error=file_exists reason=The database could not be created, the file already exists.
error=file_exists error=file_exists reason=The database could not be created, the file already exists.
Now running CMD with UID 3552 and GID 3552
time="2024-11-19T20:54:52.256+01:00" level=info msg="Started in-memory broker for 23 workers type" nspace=jobs
http server major started on "0.0.0.0:8080"
http server admin started on "0.0.0.0:6060"
time="2024-11-19T21:00:15.635+01:00" level=error msg="cannot open the geodb: no such device" nspace=sessions
time="2024-11-19T21:00:15.635+01:00" level=info msg="New connection from 192.168.1.1 at 2024-11-19 21:00:15.635562778 +0100 CET m=+323.744373986 (password)" domain=cozy.mydomain.fr nspace=loginaudit
`

Thanks to another user on Cozy forum, there is one reference to this variable in the .env template (full version) here : 
https://github.com/cozy/cozy-stack/blob/master/cozy.example.yaml#L295   (line 295)

Thanks for anyone help. Regards.

**Comment by ibaraki-douji** [comment]
@EricGuic For context i'm using the docker compose version (https://github.com/cozy/cozy-stack-compose/blob/main/docker-compose.yml)

To fix it on my end i just edited the `cozy.yml` and added the `geodb: ""` inside it.
