### ISSUE TITLE
[Exploration] Couchdb MapReduce vs Indexes

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-stack#45]
There are two ways to request documents in Couchdb2. 

### MapReduce [doc](http://wiki.apache.org/couchdb/Introduction_to_CouchDB_views)
by PUTing a `_design/xxxx` document, with a map view, which can be arbiraty complex
```javascript
// simple : sort all doc by name 
function(contact){
     emit(contact.name)
}
```
```javascript
// more complex : tags
function(note){
    for(var i=0, l=note.tags.length; i<l; i++{
         emit(note.tags[i], note.title)
    }
}
```

```javascript
// complex & arbitrary : get all done todo, sorted by hour of completion, 
// to see at what point of the day we are more efficient.
function(todo){
    if(todo.done){
         emit(new Date(todo.doneDate).getHours(), todo.complexity)
    }
}
```

This construct an index though the key (first argument of emit), which can they be requested with key=xx or sliced with startKey=xxxx... This returns the value (second argument of emit) or the full doc with include_docs=true.

This is very powerful, and allow for very complex query and statistics

### Indexes & Mango [doc](http://docs.couchdb.org/en/2.0.0/api/database/find.html)
by POSTing an index 
```json
{
    "index": { "fields": ["firstname", "lastname"]  },
}
```
we can then request it using the mango query language
```json
{
 "selector": {"firstname": "John"},
 "sort": ["lastname"],
 "limit": 2,
}
```

This is erlang powered and thus faster as there is no need to format the doc to JSON and pass it through IPC to the internal couchdb JS server. 
However it is more limited : it is impossible to do manipulation of the data (like extracting hour from the datetime in the map exemple). And, more limiting, it is impossible to emit for each value of an array or map (tag exemple - [couchdb isssue](https://issues.apache.org/jira/browse/COUCHDB-2867)).

The vast majority of query from the previous stack and application can be made using the index&mango system : sort by field, get docs where fields is x, where field start with x. 
A few query could not ( [exemple](https://github.com/cozy/cozy-emails/blob/304a6364d2a64c0f6df428b93b230abbce854cfa/server/models/requests.coffee#L13) , [exemple2](https://github.com/cozy/cozy-calendar/blob/da36ca6db78b95c8c5551e4c3ec6555737a2a1b7/server/models/requests.coffee#L39) ) 

My opinion is that we should focus on Indexes&Mango at first as it is faster, simpler and clearer for our firsts uses cases : get all files & folders by parentid. However we will need to support JS map reduce at some point in the future, but we should make it a less desirable option when proper client-side denormalisation of the document would allow to use indexes&mango (adding a completed_hour field in our task example)

**Comment by nono** [comment]
> My opinion is that we should focus on Indexes&Mango at first

:+1:

**Comment by jinroh** [comment]
Agree also. Since indexes are sufficient for our current workcases, let's focus on them first 👍
