### ISSUE TITLE
relationships.meta is empty when fetching the content of an empty folder

### ISSUE THREAD

**Issue by goldoraf** [cozy/cozy-stack#524]
When fetching a folder's contents using `GET /files/:file-id`, the returned JSON should contain a `relationships.meta.count` property (we rely on it for cozy-drive's virtualized lists). But when the folder is empty, the `relationships.meta` object is empty.

**Comment by aenario** [comment]
Info for who fixes this :

json.Marshal issue, use a pointer to int (http://stackoverflow.com/questions/38486564/golang-unmarshal-marshal-json-with-int-set-to-0-does-not-seem-to-work).
