### ISSUE TITLE
Couchdb admin credentials

### ISSUE THREAD

**Issue by e-morel** [cozy/cozy-stack#573]
Hi,
When I start the cozy-stack and try to add an instance, I have an unauthorized error.
The stack doesn't have couchdb admin logs.

How can I give those credentials to the stack ?

Thanks you

**Comment by nono** [comment]
Hello,

you can use the `--couchdb-url` flag, like this:

```
$ cozy-stack serve --couchdb-url http://user:password@localhost:5984/
```
