### ISSUE TITLE
Doctypes and databases

### ISSUE THREAD

**Issue by jinroh** [cozy/cozy-stack#58]
Storing files and directories in the same couch dabatase is mandatory to allow us faster queries (more batching, less roundtrips) and simpler document search.

However, it also has some implications regarding our current api. We have a relation doctype <-> database which makes it difficult for files and directories to live in the same database.

I list two possibilities, there can be other though..
### 1) Get rid of the doctype <-> database relation

We could remove the `DocType()` method from the couchdb.Doc interface to remove this relation, and add a "dbname" parameter to CRUD methods. ie:

```
CreateDoc(dbprefix string, *Doc) -> CreateDoc(dbprefix, dbname string, *Doc)
```

This puts the burden on the user of the couchdb package to handle document type, but is also more generic and allows to store different document on the same database.
### 2) Unique `DocType` and a new field

We could have a unique DocType for files and folders io.cozy.files. While this allow us to keep our current model, doctype <-> database, it would require either:
- to change quite heavily the current API to get rid of the notion of io.cozy.folders
- some dexterity to go from our public model to the inner one (also making the code base less clear).

What do you think ?

**Comment by nono** [comment]
The second option (with getting rid of the notion of io.cozy.folders) looks like the simpler one

**Comment by jinroh** [comment]
I'm also leaning toward this option.
This requires us to agree on some changes on the API though.

**Comment by jinroh** [comment]
Opted finally for option 2
