### ISSUE TITLE
--disable-csp flag to disable CSP ?

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-stack#649]
To have hot reloading, you need to serve your JS with webpack-dev-server and CSP disallow that. Would it be possible to have a flag on the stack that disables them ?

**Comment by gregorylegarec** [comment]
Bad idea IMHO to use `--dev` flag for that option. We need to be able to test in "real" conditions, with CSP. I suggest `--disable-csp` instead.

**Comment by enguerran** [comment]
Here is the problem in chrome browser:

![](https://i.imgur.com/xI5VNuk.png)

HMR, Hot Module Reload, does not need `inline-eval-source-map` to let webpack reload the needed changes.

According to the webpack's documentation, there is a lot of possible value for devtool: https://webpack.github.io/docs/configuration.html#devtool

![](https://i.imgur.com/PtD1G0j.png)

We could use whatever value we want as soon as it does not include an `eval` instruction, IMHO.

**Comment by enguerran** [comment]
There is another problem to use HMR in front applications served by the stack: https://github.com/cozy/cozy-template/blob/master/config/webpack.config.hot-reload.js#L17

It appears HMR needs a specific server started on another port:

![](https://i.imgur.com/hRXOf03.png)

**Comment by ptbrowne** [comment]
@gregorylegarec I agree that `--disable-csp` is clearer

@enguerran The `devtool` problem is effectively not related to the HMR problem. I made a mistake using it for `cozy-maif` and I did not know it would cause CSP problem. I replaced it by `cheap-source-map` so it is not a problem.

The problem is effectively the use of `webpack-dev-server` and that we need to load assets from another server than the cozy-stack.

Another option than to disable completely would be to add explicitely the server http://localhost:8282 to the list of authorized servers.

**Comment by clochix** [comment]
For the record, you can disable CSP in the development profile of your browser: go to `about:config` and set `security.csp.enable` to `false`.

**Comment by enguerran** [comment]
Using the browser's configuration to enable/disable CSP policies is a very high risk: if you forget you disabled it, then go on the dark-web, you'd be eaten by a BFK (Big Fat Kraken, a frightfull and ruthless monster).

**Comment by clochix** [comment]
What is the « dark-web »?
Also, I assume you have different browser profiles for developing and browsing the wild Internet, so you can safely lower the security of your development profile ;-)
