### ISSUE TITLE
        *gfs does not implement "gopkg.in/src-d/go-git.v4/utils/fs".Filesystem (missing OpenFile method)

### ISSUE THREAD

**Issue by dcasier** [cozy/cozy-stack#73]
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM golang
 ---> f69c27b2f59a
Step 2 : RUN go get github.com/cozy/cozy-stack
 ---> Running in 26412f110b09
# github.com/cozy/cozy-stack/apps
src/github.com/cozy/cozy-stack/apps/git.go:89: cannot use gfs (type *gfs) as type "gopkg.in/src-d/go-git.v4/utils/fs".Filesystem in argument to filesystem.NewStorage:
        *gfs does not implement "gopkg.in/src-d/go-git.v4/utils/fs".Filesystem (missing OpenFile method)
src/github.com/cozy/cozy-stack/apps/git.go:324: cannot use newGFS(fs.vfsC, fs.Join(fs.base, name)) (type *gfs) as type "gopkg.in/src-d/go-git.v4/utils/fs".Filesystem in return argument:
        *gfs does not implement "gopkg.in/src-d/go-git.v4/utils/fs".Filesystem (missing OpenFile method)
src/github.com/cozy/cozy-stack/apps/git.go:333: cannot use gfs literal (type *gfs) as type "gopkg.in/src-d/go-git.v4/utils/fs".Filesystem in assignment:
        *gfs does not implement "gopkg.in/src-d/go-git.v4/utils/fs".Filesystem (missing OpenFile method)

**Comment by jinroh** [comment]
A new release candidate of [go-git.v4 has been released](https://github.com/src-d/go-git/releases/tag/v4.0.0-rc2) yesterday. We have to make some changes to support this new version.

**Comment by dcasier** [comment]
Ok, 
needed: OpenFile and Remove in  vfs/file.go, vfs/vfs.go and apps/git.go

**Comment by jinroh** [comment]
When #76 lands, this issue should be fixed.
