### ISSUE TITLE
MapReduce use-case (need for reduction)

### ISSUE THREAD

**Issue by Phyks** [cozy/cozy-stack#74]
Hi,

I was working on [an app for Cozy](https://github.com/Phyks/cozy-RSVP) (really a WIP) which would implement something like [Calendly](http://calendly.com/).

TLDR: It aims at letting you set up some public endpoints to give to others, so that they can request a time slot in your calendar. Typically, if you often schedule 30mins meetings with people, you would have an endpoint to request a slot for such a meeting. Others would choose the available time slots which best suits them and you will just have to confirm or refuse it. If you confirm it, it gets automatically in your calendar. To get a better idea, you can try [this link](https://calendly.com/phyks/15min/), do not worry, it is not plugged to any of my calendars.

I was trying to write it full clientside and to avoid too much code migration when the new stack will be out. There are two main concerns about this app:
* Being able to serve a route publicly in the app (but this should be doable without concerns if I understood completely)
* Being able to perform reduction of data on the server side.

The second point is crucial for such an app. In the public route, you must have access to all events stored in the cozy, to filter out possible time slots and avoid conflicts. However, you absolutely do not want to fetch them locally, as it means an anonymous browser would handle all the events in the cozy. So this should be done server-side.

At the moment, I guess it can be done quite easily with CouchDB `MapReduce`. Basically, one would select all the events and perform reduction to only emit "conflicting time slots", that is the minimum information required, without any information about the events themselves.

As far as I understood, [cozy-stack will drop `MapReduce` in favor of `Mango` queries](https://github.com/cozy/cozy-api/blob/master/docs/browser-sdk-transition.md#mapreduce-views-vs-mango-queries). I may have missed something, but I did not find anything about a way to perform reduction on fetched data using `Mango` queries.

Thanks

**Comment by jinroh** [comment]
@Phyks Hello, we do not plan to drop `MapReduce` in favor of `Mango`, we just have focused for now on `Mango` queries since they are more performant and they meet our current needs (for the VFS most notably).

Your constraints and requirements for MapReduce are still completely valid and should be supported by the V2 stack. Sorry if we have not been clear about it in the linked issue.

I can not really give you an ETA for this feature though.

**Comment by Phyks** [comment]
OK, so the app should be working at some point with the new stack. 

I read

> If you need the full power of MapReduce, please open a issue on cozy-stack with your usecase.

So I opened an issue :)


However, I may have missed something with the mango requests and maybe the same kind of things is doable? (Basically fetch a reduction of data from a public endpoint to avoid exposing too much India)

**Comment by aenario** [comment]
Thanks for the issue @Phyks ! 

This is an interesting use case and we will take it into account when designing the public permission system.

This goes a bit further than MapReduce vs Mango and it cannot be done with client-side application in the current version of cozy : Either you dont pass the token and the public part of an application does not have access to the data at all, or if you pass the token it has access to all events.

What we need is a way to specify permission for  accessing the reduced result of a MapReduce, but not the documents themselves. 
It could also be solved by forcing the `fields` value of a Mango query : we could get a list of events datetime & rrule but not title or description. And perform matching on public client side.

Summoning @Gara64 @Ljinod as it is somewhat related to sharing.

**Comment by aenario** [comment]
(closing was a mistake)

**Comment by Phyks** [comment]
Indeed, I thought that if I was defining the view in the "private" side of the app, I could request it on the public side of the app, without exposing the actual events. But indeed, to query it, I have to have access to the token and then, an evil client can request anything in the db. So this would definitely need a server-side app for the moment ='(

I guess, there is no workaround possible at the moment? (I mean, on the v1, it is to build a server-side part for this, but for the v2, this is not yet designed?) There is no way to query CouchDB directly with a specific token leaving access to just a subset of the data? (I've just discovered CouchDB, this might be a stupid question :)

> What we need is a way to specify permission for accessing the reduced result of a MapReduce, but not the documents themselves. 

:+1:

> It could also be solved by forcing the fields value of a Mango query : we could get a list of events datetime & rrule but not title or description. And perform matching on public client side.

I am not in favor of this. I think leaking datetimes of individual events, rather than aggregate data, is way more than needed, and could help "deanonymize" the events themselves. If I have access to such untitled events of multiple cozy instances, I can match them together, and I have a good idea of the people taking part in a given event.

**Comment by nono** [comment]
We now have the notion of [services](https://cozy.github.io/cozy-stack/apps.html#services). It's JS code that can be run on the server on some events. Our first use case was to sent notifications when documents with some conditions are written (like a bill whose amount is superior to a threshold).

I think you can use a service to aggregate the events in another doctypes for free slots and give a public permissions for reading this doctype.
