### ISSUE TITLE
Can't create a Cozy instance

### ISSUE THREAD

**Issue by JulesMichael** [cozy/cozy-stack#744]
Hello,
When I execute :
``` bash
./cozy-stack instances add --dev --apps drive,settings,onboarding --passphrase cozy "cozy.tools:8080"
```
I have as result:
``` bash
# cozy-stack instances side
Failed to create instance for domain cozy.tools:8080
Error: bad_request: Referer header required.

# cozy-stack serve side
ERRO[0004] [http] POST /instances CouchDB(bad_request): Referer header required.  nspace=http
```

I don't know my Cozy version because when I type `./cozy-stack version`, I have no result. But I have clone this repo yesterday.

**Comment by nono** [comment]
Hello,
what version of couchdb are you using? What does the command `curl http://localhost:5984/_all_dbs` says?

**Comment by JulesMichael** [comment]
Ho I have CouchDb v1.4.0 and I saw that the v2.0.0 is required. Might it's that.

When I run `curl http://localhost:5984/_all_dbs` I have `["_replicator","_users","global/instances"]`

**Comment by nono** [comment]
> Ho I have CouchDb v1.4.0 and I saw in the doc that the v2.0.0 is required. Might it's that.

I really think it's the issue.

**Comment by JulesMichael** [comment]
I will try to update CouchDb on my Raspberry PI ^^
