### ISSUE TITLE
Is redis mandatory for the stack?

### ISSUE THREAD

**Issue by lespacedunmatin** [cozy/cozy-stack#844]
Should we update https://github.com/cozy/cozy-stack/blob/master/docs/INSTALL.md with infos to install redis on the server/computer ?

Like `docker pull redis` and `docker run -p 6379:6379 redis`…

**Comment by nono** [comment]
Redis is not mandatory. Most developers and self-hosted won't use it. It's only for the multi-stack: when several cozy-stack are serving requests for the same instances, they need to synchronize some things (cache, locks, sessions code,etc.) via redis. But when there is only one cozy-stack process, it can do it in memory inside its process.

**Comment by lespacedunmatin** [comment]
Redis is mandatory for realtime in Konnectors behavior : see https://github.com/cozy/cozy-collect/pull/206.

**Comment by nono** [comment]
It was due to a bug. Not sure if it was fixed or is still in our backlog
