### ISSUE TITLE
triggers/io-cozy-triggers not create during first boot

### ISSUE THREAD

**Issue by aeris** [cozy/cozy-stack#896]
On a fresh install of `cozy-stack`, `triggers/io-cozy-triggers` CouchDB database is missing and not automatically created, and so `cozy-stack serve` fails.

    DEBU[0000] request: GET triggers%2Fio-cozy-triggers/_all_docs?include_docs=true&limit=1000   domain=triggers
    DEBU[0000] CouchDB(not_found): Database does not exist.  domain=triggers

**Comment by jinroh** [comment]
Should have been fixed by #977.
