### ISSUE TITLE
Support for external authentication?

### ISSUE THREAD

**Issue by nynymike** [cozy/cozy-stack#927]
If we already have an OpenID Connect or SAML IDP can Cozy be an relying party? Perhaps auto-enroll authenticated users if they successfully authenticate at the IDP?

**Comment by nono** [comment]
Currently, Cozy can't be a relying party, and it is not in our roadmap. What is your use case for this?

**Comment by nynymike** [comment]
There are many:

1. Unless you want to implement every type of strong authentication that a customer wants to use, you'll have to rely on an external IDP.

2. Businesses have many apps. CRM, CMS, etc... your app is one of many. If you create a new silo of identity information in your app, you add to the implementation expense. Many organizations won't even look at your application unless it integrates with the existing security infrastructure.

3. You implemented a whole OAuth provider stack. Normally when integrators do this, they don't really implement all the features necessary to make it secure. Many smart software developers don't do enough research required to mitigate all the risks.  Do you want to focus on being a security expert, or on writing a great application?

4. In addition to user authentication, a central access management platform handles authorization and consent management. Especially around document sharing, this is quite challenging. New protocols like UMA (User Managed Access Protocol) define profiles of OAuth2 that make this possible.

5.  The opportunity costs of going back to fix your application to support external authentication will only grow from here. So it's better to fix it now, because so many things hang off the authentication / authorization infrastructure.

I like what you're doing. If you want to chat, you can setup a meeting with me... [http://gluu.org/booking](http://gluu.org/booking) is my calendar. 

- Mike Schwartz
Founder / CEO Gluu

**Comment by nono** [comment]
1. Yes, but in practice, there are not that much type of strong authentication wanted by our customers.

2. We don't target businesses, just people. We lack a lot of things to be relevant for businesses/organizations.

3. & 4. Cozy is a personal cloud. We can't offer a good product if we don't manage the low-level bits about authorization. So, yes, it is very complicated to have level of security and it costs. But it's a part of the value provided by Cozy and we accept to pay the price to have it.

5. I'm not sure if you are speaking of just external authentication, or also about external authorization. For just external authentication, I don't see why the cost should grow that much. For authorization, OK, but it's too important part of the value provided by Cozy for us to accept to delegate it.
