### ISSUE TITLE
Documenter l'utilisation de mail en mode dev

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-stack#931]
Pour les notifications, j'ai dû mettre en place mailhog pour visualiser les mails envoyés.

J'ai dû demander sur #front comment faire : @enguerran a écrit une documentation ici : https://github.com/cozy/cozy-drive/pull/382. Il pense et moi aussi que ce serait mieux de l'intégrer directement dans la documentation de la stack.

@nono et @jinroh vous en pensez quoi ?

**Comment by nono** [comment]
Je préfère garder la documentation de la stack comme de doc de référence et mettre ce qui est tutos dans cozy-docs-v3. Du coup, j'ai fait cette PR -> https://github.com/cozy/cozy-docs-v3/pull/20
