### ISSUE TITLE
Cozy-Stack API error system is unusable

### ISSUE THREAD

**Issue by Schoumi** [cozy/cozy-stack#940]
The actual error system of Cozy Stack API is unusable to me.
They depends on 2 or 3 different system (cozy-stack, oauth, couchdb). Each has his response system / his response syntax.

OAuth:
http error: 400
request: doctype/_find 
JSON response: `{"error":"code=400, message=Expired token"}`

CouchDB:
http error: 400
request: doctype/_find 
JSON response: ` {"error":"no_usable_index","ok":false,"reason":"There is no index available for this selector.","status":"400"}`

A request on cozy stack should have only one system of response to be usable by third party. I can't make generic request function on the stack with this.
This two error are made with the same code depends on the state of the oauth token. If it's an old token or a good one but with error on something else.

I can't use the HTTP Status Code to make a token refresh or display error to my user due to data he send or data i send. 
Use the json as determination of error type is impossible due to the fact the error message can change during lifetime of the stack/couchdb/oauth and will break things if it's the case and it depends on which system is answering to my request.

I can't present usable message to my user too.

**Comment by nono** [comment]
I agree that the HTTP status code are not coherent and it makes difficult to use the API. But we have other goals, like:

- making possible to use pouchdb as a client of the `/data` API (so, we have to use the same HTTP codes that CouchDB)
- respecting standards when possible ([OAuth 2.0 Dynamic Client Registration Management Protocol](https://tools.ietf.org/html/rfc7592))

For the refresh token thing, cozy-client-js tries to refresh the token when it receives a 4xx error (not trying to be smart), and replay the request. If it is still an error, it's something else.
